# Configuração do Gitpod para projeto React + Node.js
image:
  file: .gitpod.Dockerfile

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# Portas a serem expostas
ports:
  - port: 3000
    onOpen: open-browser
    name: React App
    description: Frontend React Application
  - port: 5000
    name: Node API
    description: Backend Node.js Server

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
# Configurações recomendadas para VS Code
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - eamodio.gitlens
